/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-17 09:17:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class noticeMainBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#cst_content{\r\n");
      out.write("    width: 852px;\r\n");
      out.write("    height: 98px;\r\n");
      out.write("    margin-bottom: 38px;\r\n");
      out.write("/*     padding: 20px 0; */\r\n");
      out.write("    border: 4px solid #efefef;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_quick li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 212px;\r\n");
      out.write("    height: 24px;\r\n");
      out.write("    padding: 74px 0 0;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    font-weight: 800;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_quick li{\r\n");
      out.write("    float: left;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    width: 211px;\r\n");
      out.write("    height: 97px;\r\n");
      out.write("}\r\n");
      out.write(".cst_quick a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: gray;\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_quick li+li{\r\n");
      out.write("    border-left: 1px solid #ededed;\r\n");
      out.write("}\r\n");
      out.write(".sub_cont .cst_quick li a:before{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("    top: 11px;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    width: 59px;\r\n");
      out.write("    height: 46px;\r\n");
      out.write("    margin-left: -30px;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_faq{\r\n");
      out.write("    width: 822px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_faq h3 {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    padding: 0 0 18px 8px;\r\n");
      out.write("    border-bottom: 1px solid #333;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 800;\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write(".sub_cont h3 {\r\n");
      out.write("    margin: 0 0 15px;\r\n");
      out.write("}\r\n");
      out.write(".sub_cont .cst_quick {\r\n");
      out.write("    width: 852px;\r\n");
      out.write("    height: 98px;\r\n");
      out.write("    margin-bottom: 38px;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".cst_noti_main{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 38px 0 0;\r\n");
      out.write("}\r\n");
      out.write(".cst_noti_main li{\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cst_noti_main .list {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    border: 1px solid #ededed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".arrow_btn01 {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("    padding: 0 9px;\r\n");
      out.write("    border: 1px solid #dbdbdb;\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    line-height: 18px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write(".arrow_btn01 {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".list a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".q{\r\n");
      out.write("    width: 800px;\r\n");
      out.write("    height: 51px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    /* border: 1px solid #efefef; */\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    border-radius: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("p.content{\r\n");
      out.write("    border:1px solid #efefef;\r\n");
      out.write("    width: 760px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-top:5px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write(".cst_quick img{\r\n");
      out.write("    border:2px;\r\n");
      out.write("    width:90px;\r\n");
      out.write("    height:90px;\r\n");
      out.write("    padding: 10PX;\r\n");
      out.write("    margin-top: -50PX;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".couns_tbl th, .couns_tbl td {\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    padding: 8px 0 8px 18px;\r\n");
      out.write("    border-bottom: 1px solid #ededed;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("tbody {\r\n");
      out.write("    display: table-row-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".couns_tbl {\r\n");
      out.write("    width: 860px;\r\n");
      out.write("    border: 1px solid #dbdbdb;\r\n");
      out.write("    border-width: 1px 0;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    min-width: 100%;\r\n");
      out.write("    max-width: none;\r\n");
      out.write("    table-layout: fixed;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"cst_content\" class=\"sub_cont\">\r\n");
      out.write("\t\r\n");
      out.write("        <ul class=\"cst_quick\">\r\n");
      out.write("            <li class=\"q01\"><a href=\"\"><img id=\"q01\" src=\"../../resources/img/lock.png\">아이디/비밀번호 찾기</a></li>\r\n");
      out.write("            <li class=\"q02\"><a href=\"\"><img id=\"q02\" src=\"../../resources/img/delivery.png\">주문/배송 조회</a></li>\r\n");
      out.write("            <li class=\"q03\"><a href=\"\"><img id=\"q03\" src=\"../../resources/img/returnback.png\">취소/반품 내역</a></li>\r\n");
      out.write("            <li class=\"q04\"><a href=\"\"><img id=\"q04\" src=\"../../resources/img/Account.png\">비회원 주문조회</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"cst_faq\">\r\n");
      out.write("            <h3 class=\"thm\">자주 하는 질문 <span>TOP5</span></h3>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q\">반품 언제 되나요?</div>\r\n");
      out.write("            <p class=\"content\">지금 확인 중 입니다.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q\">상품 위치를 알고싶습니다.</div>\r\n");
      out.write("            <p class=\"content\">배송조회 해보세요. 거기 나와요</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q\">이 사이즈 있나요?</div>\r\n");
      out.write("            <p class=\"content\">네 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q\">아이스박스는 수거 하시나요?</div>\r\n");
      out.write("            <p class=\"content\">포장재인 아이스박스는 수거하지 않습니다.<br>\r\n");
      out.write("\r\n");
      out.write("              \t  아이스박스 수거 및 폐기시 발생되는 제반환경 및 법적조치 등 사전에 해결해야 할 사안들이 많다 보니,  당장의 회수 약속을 드리기에 어려움이 있습니다.<br>\r\n");
      out.write("                \r\n");
      out.write("                                  더반찬에서도 적극적인 대안마련과 다양한 방법을 찾기 위해 최선을 다하고 있습니다. 번거로우시겠지만, 당분간은 자체 폐기를 부탁드립니다.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"q\">신선식품인데 택배로 받아도 안전한가요?</div>\r\n");
      out.write("            <p class=\"content\">더반찬의 제품은 배송시 선도 유지를 위해 얼린 샘물을 동봉하여 아이스박스에 포장하고 있습니다. 얼린 샘물의 수량은 기온에 따라 수량이 변경되고 있습니다. 신선하고 안전하게 배송하겠습니다</p>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cst_noti_main\">\r\n");
      out.write("            <h3>공지사항</h3>\r\n");
      out.write("            <ul class=\"list\">\r\n");
      out.write("            \r\n");
      out.write("                <li><a href=\"\">[공지] 4월 국회의원선거일 배송 안내<span class=\"date thm\">2020-04-08</span></a></li>\r\n");
      out.write("            \r\n");
      out.write("                <li><a href=\"\">[공지] 업체 신선 배송 오픈 안내<span class=\"date thm\">2020-04-07</span></a></li>\r\n");
      out.write("            \r\n");
      out.write("                <li><a href=\"\">[공지] 빠른도착 카테고리 오픈 안내<span class=\"date thm\">2020-04-07</span></a></li>\r\n");
      out.write("            \r\n");
      out.write("            </ul>\r\n");
      out.write("            <a href=\"javascript:;\" onclick=\"overpass.custcenter.goNoticeList()\" class=\"arrow_btn01\">전체보기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                $(function(){\r\n");
      out.write("                    $(\".q\").click(function(){\r\n");
      out.write("            \r\n");
      out.write("                        var p = $(this).next();\r\n");
      out.write("            \r\n");
      out.write("                        if(p.css(\"display\") == \"none\"){\r\n");
      out.write("                            $(this).siblings(\"p\").slideUp();\r\n");
      out.write("                            p.slideDown();\r\n");
      out.write("                        }else{\r\n");
      out.write("                            p.slideUp();\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("            </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
